config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'vuecasts#home'

  get 'vuecasts', to: 'vuecasts#index'
  get 'vuecasts/basic_data_binding'
  get 'vuecasts/lists'
  get 'vuecasts/vue_event_listeners'
  get 'vuecasts/attribute_and_class_binding'
  get 'vuecasts/the_need_for_computed_properties'
  get 'vuecasts/components_101'

  get 'vuemastery', to: 'vuemastery#index'
  get 'vuemastery/the_vue_instance'
  get 'vuemastery/attribute_binding'
  get 'vuemastery/conditional_rendering'
  get 'vuemastery/list_rendering'
  get 'vuemastery/event_handling'
  get 'vuemastery/class_and_style_binding'
  get 'vuemastery/computed_properties'
  get 'vuemastery/components'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vuecasts_controller.rb
class VuecastsController < ApplicationController
  def home; end
  def index; end
  def basic_data_binding; end
  def lists; end
  def vue_event_listeners; end
  def attribute_and_class_binding; end
  def the_need_for_computed_properties; end
  def components_101; end
end

app/controllers/vuemastery_controller.rb
class VuemasteryController < ApplicationController
  def index; end
  def the_vue_instance; end
  def attribute_binding; end
  def conditional_rendering; end
  def list_rendering; end
  def event_handling; end
  def class_and_style_binding; end
  def computed_properties; end
  def components; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vuecasts_helper.rb
module VuecastsHelper
end

app/helpers/vuemastery_helper.rb
module VuemasteryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vuecasts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vuecasts/attribute_and_class_binding.html.erb
<h1>Vuecasts#attribute_and_class_binding</h1>

<%= link_to nil, 'https://laracasts.com/series/learn-vue-2-step-by-step/episodes/5' %>

<p></p>

<div id="vuecasts-attribute-and-class-binding" v-cloak>
  <h1 :class="className">Hello World</h1>

  <button :class="{'is-loading':isLoading}" @click="toggleClass">Click Me</button>

  <button :title="title">Hover Over Me</button>
  <!-- <button v-bind:title="title">Hover Over Me</button> -->
  <!-- <button title="I am the title of the button.">Hover Over Me</button> -->
</div>

app/views/vuecasts/basic_data_binding.html.erb
<h1>Vuecasts#basic_data_binding</h1>
<p>Find me in app/views/vuecasts/basic_data_binding.html.erb</p>

<%= link_to nil, 'https://laracasts.com/series/learn-vue-2-step-by-step/episodes/1' %>

<p></p>

<div id="root" v-cloak>
  <input type="text" id="input" v-model="message">

  <p>The value of the input is: {{ message }}.</p>
</div>

app/views/vuecasts/components_101.html.erb
<h1>Vuecasts#components_101</h1>

<%= link_to nil, 'https://laracasts.com/series/learn-vue-2-step-by-step/episodes/7' %>

<p></p>

<div id="vuecasts-components_101" v-cloak>
  <task>Go to the store</task>
  <task>Go to the bank</task>
  <task>Go to work</task>
</div>

app/views/vuecasts/home.html.erb
<h1>Vuecasts#home</h1>
<p>Find me in app/views/vuecasts/home.html.erb</p>

<%= link_to 'Source Code', 'https://github.com/Jelkster/vuecasts' %>

<ol>
  <li><%= link_to 'Vuecasts', vuecasts_path %></li>
  <li><%= link_to 'Vue Mastery', vuemastery_path %></li>
</ol>

app/views/vuecasts/index.html.erb
<h1>Vuecasts#index</h1>
<p>Find me in app/views/vuecasts/index.html.erb</p>

<%= link_to nil, 'http://vuecasts.com' %>

<ol>
  <li><%= link_to 'Basic Data Binding', vuecasts_basic_data_binding_path %></li>
  <li>Setup Vue Devtools</li>
  <li><%= link_to 'Lists', vuecasts_lists_path %></li>
  <li><%= link_to 'Vue Event Listeners', vuecasts_vue_event_listeners_path %></li>
  <li><%= link_to 'Attribute and Class Binding', vuecasts_attribute_and_class_binding_path %></li>
  <li><%= link_to 'The Need for Computed Properties', vuecasts_the_need_for_computed_properties_path %></li>
  <li><%= link_to 'Components 101', vuecasts_components_101_path %></li>
</ol>

app/views/vuecasts/lists.html.erb
<h1>Vuecasts#lists</h1>

<%= link_to nil, 'https://laracasts.com/series/learn-vue-2-step-by-step/episodes/3' %>

<p></p>

<div id="root-lists">
  <ul>
    <!-- <li v-for="name in names">{{ name }}</li> -->
    <li v-for="name in names" v-text="name"></li>
  </ul>
  <!-- $vm0.names.push('Susan') -->

  <input id="input" type="text">
  <button id="button">Add Name</button>
</div>

app/views/vuecasts/the_need_for_computed_properties.html.erb
<h1>Vuecasts#the_need_for_computed_properties</h1>

<%= link_to nil, 'https://laracasts.com/series/learn-vue-2-step-by-step/episodes/6' %>

<p></p>

<div id="vuecasts-the_need_for_computed_properties" v-cloak>
  <h1>{{ reversedMessage }}</h1>

  <h2>All Tasks</h2>
  <ul>
    <li v-for="task in tasks" v-text="task.description"></li>
  </ul>

  <h2>Incomplete Tasks</h2>
  <ul>
    <li v-for="task in incompleteTasks" v-text="task.description"></li>
  </ul>
</div>

app/views/vuecasts/vue_event_listeners.html.erb
<h1>Vuecasts#vue_event_listeners</h1>

<%= link_to nil, 'https://laracasts.com/series/learn-vue-2-step-by-step/episodes/4' %>

<p></p>

<div id="vuecasts-vue-event-listeners">
  <ul>
    <!-- <li v-for="name in names">{{ name }}</li> -->
    <li v-for="name in names" v-text="name"></li>
  </ul>
  <!-- $vm0.names.push('Susan') -->

  <input id="input" type="text" v-model="newName">
  <button @click="addName">Add Name</button>
  <!-- <button v-on:click="addName">Add Name</button> -->
  <!-- <button id="button">Add Name</button> -->
</div>

app/views/vuemastery/attribute_binding.html.erb
<h1>Vuemastery#attribute_binding</h1>
<p>Find me in app/views/vuemastery/attribute_binding.html.erb</p>

<div id="vuemastery-attribute-binding" v-cloak>
  <a :href="href">{{ href }}</a>
</div>

app/views/vuemastery/class_and_style_binding.html.erb
<h1>Vuemastery#class_and_style_binding</h1>

<%= link_to nil, 'https://www.vuemastery.com/courses/intro-to-vue-js/class-&-style-binding' %>

<div id="vuemastery-class-and-style-binding" v-cloak>
  <h1>{{ product }}</h1>
  <p>{{ image }}</p>
  <p v-if="inStock">In Stock</p>
  <p v-else>Out of Stock</p>

  <ul>
    <li v-for="detail in details">{{ detail }}</li>
  </ul>

  <div v-for="variant in variants"
       :key="variant.variantId"
       class="color-box"
       :style="{backgroundColor: variant.variantColor}"
       @mouseover="updateProduct(variant.variantImage)">
  </div>

  <!--
    You can bind an entire class object or array of classes to an element
    :class="classObject"
    :class="[activeClass, errorClass]"
  -->

  <button v-on:click="addToCart">Add to cart</button>
  <!-- <button v-on:click="cart += 1">Add to cart</button> -->

  <div class="cart">
    <p>Cart ({{cart}})</p>
  </div>
</div>

app/views/vuemastery/components.html.erb
<h1>Vuemastery#components</h1>

<%= link_to nil, 'https://www.vuemastery.com/courses/intro-to-vue-js/components' %>

<div id="vuemastery-components" v-cloak>
  <product :premium="premium"></product>
  <!-- <product></product>
  <product></product> -->
</div>

app/views/vuemastery/computed_properties.html.erb
<h1>Vuemastery#computed_properties</h1>

<%= link_to nil, 'https://www.vuemastery.com/courses/intro-to-vue-js/computed-properties' %>

<div id="vuemastery-computed-properties" v-cloak>
  <h1>{{ title }}</h1>
  <h1>{{ title }}</h1>
  <h1>{{ nonComputedTitle() }}</h1>
  <h1>{{ nonComputedTitle() }}</h1>
  <p>{{ image }}</p>
  <p v-if="inStock">In Stock</p>
  <p v-else>Out of Stock</p>

  <ul>
    <li v-for="detail in details">{{ detail }}</li>
  </ul>

  <div v-for="(variant, index) in variants"
       :key="variant.variantId"
       class="color-box"
       :style="{backgroundColor: variant.variantColor}"
       @mouseover="updateProduct(index)">
  </div>

  <button v-on:click="addToCart">Add to cart</button>

  <div class="cart">
    <p>Cart ({{cart}})</p>
  </div>
</div>

app/views/vuemastery/conditional_rendering.html.erb
<h1>Vuemastery#conditional_rendering</h1>
<p>Find me in app/views/vuemastery/conditional_rendering.html.erb</p>

<div id="vuemastery-conditional-rendering" v-cloak>
  <h1>{{ product }}</h1>
  <!-- <p v-if="inStock">In Stock</p> -->
  <p v-show="inStock">In Stock</p>
  <!-- <p v-if="inventory > 10">In Stock</p>
  <p v-else-if="inventory < 10 && inventory > 0">Almost sold out!</p>
  <p v-else>Out of Stock</p> -->
</div>

app/views/vuemastery/event_handling.html.erb
<h1>Vuemastery#event_handling</h1>

<%= link_to nil, 'https://www.vuemastery.com/courses/intro-to-vue-js/event-handling' %>

<div id="vuemastery-event-handling" v-cloak>
  <h1>{{ product }}</h1>
  <p>{{ image }}</p>
  <p v-if="inStock">In Stock</p>
  <p v-else>Out of Stock</p>

  <ul>
    <li v-for="detail in details">{{ detail }}</li>
  </ul>

  <div v-for="variant in variants" :key="variant.variantId">
    <p @mouseover="updateProduct(variant.variantImage)">{{ variant.variantColor }}</p>
  </div>

  <button v-on:click="addToCart">Add to cart</button>
  <!-- <button v-on:click="cart += 1">Add to cart</button> -->

  <div class="cart">
    <p>Cart ({{cart}})</p>
  </div>
</div>

app/views/vuemastery/index.html.erb
<h1>Vuemastery#index</h1>
<p>Find me in app/views/vuemastery/index.html.erb</p>

<%= link_to nil, 'https://www.vuemastery.com' %>

<h2>Intro to Vue.js</h2>

<ol>
  <li><%= link_to 'The Vue Instance', vuemastery_the_vue_instance_path %></li>
  <li><%= link_to 'Attribute Binding', vuemastery_attribute_binding_path %></li>
  <li><%= link_to 'Conditional Rendering', vuemastery_conditional_rendering_path %></li>
  <li><%= link_to 'List Rendering', vuemastery_list_rendering_path %></li>
  <li><%= link_to 'Event Handling', vuemastery_event_handling_path %></li>
  <li><%= link_to 'Class & Style Binding', vuemastery_class_and_style_binding_path %></li>
  <li><%= link_to 'Computed Properties', vuemastery_computed_properties_path %></li>
  <li><%= link_to 'Components', vuemastery_components_path %></li>
</ol>

app/views/vuemastery/list_rendering.html.erb
<h1>Vuemastery#list_rendering</h1>
<p>Find me in app/views/vuemastery/list_rendering.html.erb</p>

<%= link_to nil, 'https://www.vuemastery.com/courses/intro-to-vue-js/list-rendering' %>

<div id="vuemastery-list-rendering" v-cloak>
  <h1>{{ product }}</h1>
  <p v-if="inStock">In Stock</p>
  <p v-else>Out of Stock</p>

  <ul>
    <li v-for="detail in details">{{ detail }}</li>
  </ul>

  <div v-for="variant in variants" :key="variant.variantId">
    <p>{{ variant.variantColor }}</p>
  </div>
</div>

app/views/vuemastery/the_vue_instance.html.erb
<h1>Vuemastery#the_vue_instance</h1>
<p>Find me in app/views/vuemastery/the_vue_instance.html.erb</p>

<%= link_to nil, 'https://www.vuemastery.com/courses/intro-to-vue-js/vue-instance' %>

<div id="vuemastery-the-vue-instance" v-cloak>
  <h1>{{ product }}</h1>
</div>